apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: synthema-dev
data:
  MINIO_ENDPOINT: "obstorageapi.k8s.synthema.rid-intrasoft.eu:9090"
  MINIO_BUCKET_NAME: "data-annotation"
