apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: synthema-dev
type: Opaque
data:
  MINIO_ACCESS_KEY: "bXFjcXdFQ3ZvZ2E2cGtEUmhPVXo="  # Run: echo -n "your-access-key" | base64 mqcqwECvoga6pkDRhOUz
  MINIO_SECRET_KEY: "RU42dDFUV1pFTFJobjFMeUdvaTZ1YnRBcG1Yb1VKZnNueTl0Ull6OQ=="  # Run: echo -n "your-secret-key" | base64 EN6t1TWZELRhn1LyGoi6ubtApmXoUJfsny9tRYz9
  MINIO_BUCKET_NAME: "ZGF0YS1hbm5vdGF0aW9u" #base 64 data-annotation
