pipeline {
    agent {
        node {
            label 'jenkins-dev'
        }
    }
    parameters {
        string(name: 'K8S_NAMESPACE', defaultValue: 'synthema-dev', description: 'Existing target namespace for all service resources')
    }
    options { disableConcurrentBuilds() }
    environment {
        APP_NAME = "data-ingestor"
        MAJOR_RELEASE = 0.1
        DOCKER_TAG = "${MAJOR_RELEASE}.${env.BUILD_NUMBER}"
        DOCKER_REG = "harbor.synthema.rid-intrasoft.eu"
        DOCKER_REPO = "/synthema/"
        DOCKER_REG_CREDS = "harbor-jenkins-creds"
        MINIO_ENDPOINT = "obstorageapi.k8s.synthema.rid-intrasoft.eu"
        MINIO_ACCESS_KEY = "mqcqwECvoga6pkDRhOUz" //credentials("MINIO_ACCESS_KEY")
        MINIO_SECRET_KEY = "EN6t1TWZELRhn1LyGoi6ubtApmXoUJfsny9tRYz9" //credentials("MINIO_SECRET_KEY")
        MINIO_BUCKET_NAME = "data-annotation"
    }

    stages {
        // *************************
        // *** IMAGE BUILD STAGE ***
        // *************************
        stage("Build_Images"){
            steps {
                echo "***** Building Image *****"
                // Build the image and push a test tag to the remote repository
                sh 'docker image build -t ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:test src'
                sh 'docker image push ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:test'
            }
        }

        // **************************
        // *** RUN THE UNIT TESTS ***
        // **************************
        stage("Unit_Tests"){
            steps{
                sh 'docker container run -e "PYTHONPATH=/tests" -e MINIO_ENDPOINT="${MINIO_ENDPOINT}" -e MINIO_ACCESS_KEY="${MINIO_ACCESS_KEY}" -e MINIO_SECRET_KEY="${MINIO_SECRET_KEY}" -e MINIO_BUCKET_NAME="${MINIO_BUCKET_NAME}" --name ${APP_NAME}_test_$(date +%s) --rm ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:test python -m pytest tests/unit.py tests/test_csv_input.py tests/test_partitioned_upload.py'
            }
        }

        // **************************************
        // *** Functional & Integration Tests ***
        // **************************************

        // *******************************
        // *** Push Images To Registry ***
        // *******************************
        stage("Push_Image"){
            when {
                environment name: "GIT_BRANCH", value: "origin/dev"
            }
            steps {
                withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'harbor-jenkins-creds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]){
                    echo "***** Push Container Image *****"
                    // Login to the remote Docker Registry
                    sh 'docker login ${DOCKER_REG} -u ${USERNAME} -p ${PASSWORD}'
                    // Build the images
                    sh 'docker image tag ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:test ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:latest'
                    sh 'docker image tag ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:test ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}'
                    sh 'docker image push ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}'
                    sh 'docker image push ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:latest'
                }
            }
        }
        // **************
        // *** Deploy ***
        // **************
        stage("Deployment"){
            when {
                environment name: "GIT_BRANCH", value: "origin/dev"
            }

            steps {
                withKubeConfig([credentialsId: 'k8s-admin']) {
                    sh '''
                    bash jenkins/deploy.sh
                    '''
               }
            }
        }
    }
    post{
        always {
            echo "***** Cleaning Up *****"
            // Clean up the Docker resources
            sh '''
            docker image rm ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG} || true
            docker image rm ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:latest || true
            docker image rm ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:test || true
            '''
        }
        // failure{
        // //     // slackSend (color: "#FF0000", message: "Job FAILED: '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
        // //     sh 'docker image rm ${APP_NAME}:test &> /dev/null || True'
        // //     sh 'DOCKER_TAG=test docker compose down --rmi all'
        // }

        // success{
        //     slackSend (color: "#008000", message: "Job SUCCESSFUL: '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
        // }
    }
}
